### ISSUE TITLE
Pelican's extractor crashes

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#50]
On `amy01` exporter crashes after roughly 100-150k extracted releases which causes that collection starts to be processed from the start. Eventually it was a never ending story which produced 80 datasets in pelican before I stopped it.

```
021-05-27 06:32:23,867 - ocds_kingfisher_extractor - INFO - Inserted page 136 from 263. 136000 items out of 262537 downloaded
2021-05-27 06:32:31,998 - ocds_kingfisher_extractor - INFO - Inserted page 137 from 263. 137000 items out of 262537 downloaded
2021-05-27 06:32:37,557 - ocds_kingfisher_extractor - INFO - Inserted page 138 from 263. 138000 items out of 262537 downloaded
2021-05-27 06:32:42,085 - ocds_kingfisher_extractor - ERROR - Something went wrong when processing b'{"name": "honduras_oncae_2021-05-26T09:33:40_12", "collection_id": 86}'
Traceback (most recent call last):
  File "/usr/src/app/extractor/ocds_kingfisher.py", line 169, in callback
    publish(json.dumps(message), get_param("exchange_name") + routing_key)
  File "/usr/src/app/tools/rabbit.py", line 17, in publish
    properties=pika.BasicProperties(delivery_mode=2),
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2248, in basic_publish
    self._flush_output()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1340, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (406, 'PRECONDITION_FAILED - consumer ack timed out on channel 1')
2021-05-27 06:32:43,581 - ocds_kingfisher_extractor - DEBUG - Connecting to db...
2021-05-27 06:32:43,587 - ocds_kingfisher_extractor - INFO - DB connection established
2021-05-27 06:32:43,587 - ocds_kingfisher_extractor - DEBUG - Setting schema to production, postgis, public
2021-05-27 06:32:45,605 - ocds_kingfisher_extractor - DEBUG - OCDS Kingfisher extractor initialized.
2021-05-27 06:32:45,605 - ocds_kingfisher_extractor - INFO - Starting currency exchange rates update.
2021-05-27 06:32:45,607 - ocds_kingfisher_extractor - INFO - Last available date is 2021-05-26. Total of 1 day(s) will be updated.
2021-05-27 06:32:45,607 - ocds_kingfisher_extractor - INFO - Fetching exchange rates for 2021-05-26.
2021-05-27 06:32:45,841 - ocds_kingfisher_extractor - INFO - Exchange rates update finished.
2021-05-27 06:32:45,842 - ocds_kingfisher_extractor - DEBUG - Connecting to RabbitMQ...
2021-05-27 06:32:45,847 - ocds_kingfisher_extractor - INFO - RabbitMQ connection established
2021-05-27 06:32:45,849 - ocds_kingfisher_extractor - DEBUG - Consuming messages from exchange dqt_production with routing key dqt_production_ocds_kingfisher_extractor_init
```

**Comment by jakubkrafka** [comment]
Fixed and deployed.
