### ISSUE TITLE
Pelican API timeout when CBOM trying to get information about the dataset

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#91]
Chile compra record (pelican_id = 1057) contains more than 1.6M compiled releases and it looks like it takes too much time to get the results

`dqv_django_1` log
```
[2021-07-22 07:38:54 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:17)
[2021-07-22 07:38:55 +0000] [7] [WARNING] Worker with pid 17 was terminated due to signal 9
[2021-07-22 07:38:55 +0000] [176] [INFO] Booting worker with pid: 176
```

`data-registry_cbom_1` log
```
[22/Jul/2021 07:47:38] DEBUG [cbom:20] Processing collection Chile - Compra records (10)
[22/Jul/2021 07:48:09] ERROR [cbom:115] Unable get dataset availability from pelican
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/data_registry/cbom/utils.py", line 11, in request
    resp = requests.request(method, url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/data_registry/cbom/process.py", line 180, in update_collection_availability
    resp = request(
  File "/usr/src/app/data_registry/cbom/utils.py", line 15, in request
    raise RecoverableException(error_msg) from e
data_registry.cbom.task.exceptions.RecoverableException: Request on http://localhost:8001/api/dataset_availability/1057 failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/data_registry/cbom/process.py", line 111, in process
    update_collection_availability(job)
  File "/usr/src/app/data_registry/cbom/process.py", line 185, in update_collection_availability
    raise Exception("Unable get dataset availability from pelican") from e
Exception: Unable get dataset availability from pelican
```

**Comment by jakubkrafka** [comment]
Increased processing timeout.
